### ISSUE TITLE
No rules found for this video - Firefox

### ISSUE THREAD

**Issue by niklas-lu** [dieserRobin/canireact-extension#6]
Die Extension funktioniert bei mir in Chromium aber nicht in Firefox.

Environment:
* OS: Ubuntu 24.04
* Firefox 125.0.2 (64-bit) Mozilla Firefox Snap for Ubuntu: Extensions außer canireact deaktiviert
* Chromium Version 125.0.6422.112 (Official Build) snap (64-bit): Keine Extensions außer canireact

In Chromium wird alles korrekt angezeigt:
![image](https://github.com/dieserRobin/canireact-extension/assets/61416161/ca4e05ae-b845-4bab-bd2c-a2b18ccbc937)

In Firefox jedoch nicht: 
![image](https://github.com/dieserRobin/canireact-extension/assets/61416161/19e2f138-7dbd-47f2-af71-16a70abc880c)

Braucht ihr noch etwas zusätzliches oder hab ich irgendwas vergessen, dass es in Firefox nicht geht?

**Comment by dieserRobin** [comment]
moino, danke für deinen bug report :) 

scheint, dass bei firefox die production environment erkennung noch nicht richtig funktioniert. setze mich sofort an einen fix

**Comment by dieserRobin** [comment]
Die neue Version mit dem fix ist im Firefox Store, um manuell zu updaten, öffne `about:addons`, wähle Can I React und Suche über das Zahnrad nach einer neuen Version

**Comment by niklas-lu** [comment]
Das ging schnell xD jetzt geht es auch in Firefox. Danke dir
