### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by AnimeHeaven** [dieserRobin/canireact-extension#7]
Wenn ich mich auf der Webseite mit meinem Google Account einloggen möchte, kann ich bis zu den Zugriffsrechte (sprich; Can I React? möchte zusätzliche Zugriffsrechte für Ihr Google-Konto) alles machen, auch die Rechte vergeben. Klicke ich auf weiter, erscheint der Fehler 404 not found. 
Dabei werde ich auf die Seite:

https://api.canireact.com/auth/callback/google?code=CODE&scope=email%20profile%20openid%20https://www.googleapis.com/auth/youtube.readonly%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent 

weitergeleitet.

**Comment by dieserRobin** [comment]
Danke für die Meldung, schau’ ich mir sofort an

**Comment by dieserRobin** [comment]
Scheinbar überschreiten wir gerade die Quota Limits von YouTube und müssen einen neuen Antrag stellen. 😪

**Comment by AnimeHeaven** [comment]
> Scheinbar überschreiten wir gerade die Quota Limits von YouTube und müssen einen neuen Antrag stellen. 😪

Na so schnell kann es gehen :D

**Comment by Pillowg1rl** [comment]
So schnell gehts :D Einmal bei Gronkh im Stream gefeatured :D

**Comment by marcus85nrw** [comment]
Wann kann man denn damit rechnen, dass man sich wieder eintragen kann? Ist die Freigabe absehbar? :)

**Comment by dieserRobin** [comment]
> Wann kann man denn damit rechnen, dass man sich wieder eintragen kann? Ist die Freigabe absehbar? :)

Ich hoffe im Laufe der nächsten Woche  :)

**Comment by dieserRobin** [comment]
Die neue Website mit der Möglichkeit zum erstellen neuer Guidelines ist jetzt seit ein paar Tagen online.
