### ISSUE TITLE
Date for allowed_after_hours messages

### ISSUE THREAD

**Issue by rettichlp** [dieserRobin/canireact-extension#8]
Hey, vielleicht hast du es gerade auch im Stream gesehen, aber es wurde sich ein Datum bzw. Countdown gewünscht bei den beiden Nachrichten:
- `stream_reactions_allowed_after_hours`
- `video_reactions_allowed_after_hours`

**Comment by dieserRobin** [comment]
yes, das kann ich auf jeden fall hinzufügen, danke dir :)

**Comment by dieserRobin** [comment]
Die neuen Versionen mit dem Feature sind bei den Stores hochgeladen o7
