### ISSUE TITLE
Frage bezüglich API Infos

### ISSUE THREAD

**Issue by JuniorWolfgamingDE** [dieserRobin/canireact-extension#9]
Hey :D
Habe da ein paar Fragen. Woher kommen denn die Guideline-Infos die von der Extension genutzt werden? Funktioniert das ganze derzeit nur mit den von 1UP verwalteten Kanälen, oder kann man auch irgendwie Infos für seinen eigenen Kanal zur API hinzufügen? 

Wäre schön wenn die Fragen bei Gelegenheit beantwortet werden, denn die Idee der Extension finde ich klasse.

**Comment by dieserRobin** [comment]
Wir schreiben aktuell aktiv viele Kanäle an und fragen nach den Guidelines. Das Einsenden eigener Guidelines geht normal über die Website, ist aber aktuell pausiert, weil Google unseren Zugang gesperrt hat lol, sollte aber bald wieder da sein.

**Comment by JuniorWolfgamingDE** [comment]
Ah 😅
Hoffen wir dass Google sich schnell wieder einkriegt. Vielen Dank für die schnelle Antwort!
